network_params:
  network_id: "3151908"
  genesis_delay: -1
  deneb_fork_epoch: 0
  electra_fork_epoch: 999999
  preregistered_validator_count: -1     # This is overwritten by DIVA

diva_params:
  diva_validators: 55
  diva_nodes: 5
  diva_val_type: prysm 

  options:
    deploy_eth: true
    deploy_diva_nodes: true
    deploy_diva_sc: false
    deploy_diva_coord_boot: true
    deploy_operator_ui: false
    charge_pre_genesis_keys: true
    private_pools_only: true  
    public_ports: false
    verify_fee_recipient: false
    eth_connection_enabled: false
  use_w3s: false

participants:
  - el_type: geth
    cl_type: prysm
    validator_count: 32

  - el_type: geth
    cl_type: prysm
    validator_count: 0

# Ethereum nodes for diva connections
# Nodes with 0 validators will be used by diva nodes uniformely distributed
  - el_type: geth
    cl_type: prysm
    validator_count: 32

additional_services:
  #- tx_spammer
  #- blob_spammer
  #- custom_flood
  #- el_forkmon
  #- beacon_metrics_gazer
  - dora
  #- prometheus_grafana
  #- full_beaconchain_explorer

persistent: false

mev_params:
  launch_custom_flood: true
  mev_relay_image: flashbots/mev-boost-relay:latest

mev_type: null
