network_params:
  genesis_delay: 30
participants:
  - el_client_type: geth
    cl_client_type: teku
    cl_split_mode_enabled: true
    validator_count: 1

  - el_client_type: geth
    cl_client_type: nimbus
    validator_count: 65  