network_params:
  network_id: "3151908"
  genesis_delay: 10 #-1                 # If -1, it is overwritten by DIVA
  deneb_fork_epoch: 0
  electra_fork_epoch: 999999
  preregistered_validator_count: -1     # If -1, it is overwritten by DIVA
  preset: minimal

diva_params:
  diva_validators: 0
  diva_nodes: 5
  diva_val_type: nimbus
  distribution: "[]"                    # Array-index is node-index and array value is number of keyshares, if empty will be randomly distributed
  
  options:
    deploy_eth: true
    deploy_diva_nodes: true
    deploy_diva_coord_boot: true
    deploy_diva_sc: true
    deploy_oracle: false

    deposit_operators_eth: 70
    diva_prover: true
    diva_submitter: true
    diva_heartbeat: true

    private_pools_only: false           # TODO: validar diva_sc and eth_true and nodes_true
    deploy_operator_ui: false
    public_ports: false
    verify_fee_recipient: false
    eth_connection_enabled: true
    debug_nodes: false
    tracing: false
  use_w3s: false

participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.13.15
    #el_extra_params: ["--gcmode=archive"]
    cl_type: prysm
    cl_extra_params: ["--enable-debug-rpc-endpoints"]
    validator_count: 128
    use_separate_vc: true
    count: 2
# Ethereum nodes for diva connections
# Nodes with 0 validators will be used by diva nodes and connections will be uniformely distributed between them

additional_services:
  #- tx_spammer
  #- blob_spammer
  #- custom_flood
  #- el_forkmon
  #- beacon_metrics_gazer
  - dora
  #- prometheus_grafana
  #- full_beaconchain_explorer
  - blockscout

persistent: false
mev_type: null
