network_params:
  network_id: "3151908"
  genesis_delay: 60
  deneb_fork_epoch: 900
  electra_fork_epoch: null
  preregistered_validator_count: 66 #Those not assigned in participats will be available for diva

additional_services: 
  - dora
  - blockscout
mev_type: none

participants:
  # first pair must be geth & nimbus to expose public ports if you use shamir eth-pack
  - el_client_type: geth
    cl_client_type: nimbus
    validator_count: 32

  - el_client_type: geth
    cl_client_type: nimbus
    validator_count: 32

diva_params:
  deployment:
    deploy_eth: false
    deploy_diva_sc: true
    deploy_diva_coord_boot: true
    deploy_diva: false
    deploy_operator_ui: false
    options:
      charge_pre_genesis_keys: false
      public_ports: true

  protocol_features:
    verify_fee_recipient: false
    private_pools_only: true
  
persistent: false
