network_params:
  genesis_delay: 60
  
additional_services:
  - dora
  - custom_flood

mev_type: full

participants:
  - el_client_type: geth
    cl_client_type: lighthouse
    validator_count: 2

  - el_client_type: geth
    cl_client_type: nimbus
    validator_count: 68

diva_params:
  verify_fee_recipient: false
  deploy_diva: true
  deploy_eth:
    deploy_eth_clients: true
    deploy_diva_sc: true
    deploy_diva_coord_boot: true


mev_params:
  launch_custom_flood: true