network_params:
  network_id: "3151908"
  genesis_delay: 10 #-1                 # If -1, it is overwritten by DIVA
  deneb_fork_epoch: 0
  electra_fork_epoch: 999999
  preregistered_validator_count: -1     # If -1, it is overwritten by DIVA
  eth1_follow_distance: 8
  epochs_per_eth1_voting_period: 2
diva_params:
  diva_validators: 1
  diva_nodes: 5
  diva_val_type: prysm 
  distribution: "[]"                    # Array-index is node-index and array value is number of keyshares, if empty will be randomly distributed
  
  options:
    deploy_eth: true
    deploy_diva_nodes: true
    deploy_diva_sc: true
    private_pools_only: false           # TODO: validar diva_sc and eth_true and nodes_true
    deploy_diva_coord_boot: true
    deploy_operator_ui: false
    charge_pre_genesis_keys: true
    public_ports: false
    verify_fee_recipient: false
    eth_connection_enabled: true
    debug_nodes: false
  use_w3s: false

participants:
  - el_type: geth
    cl_type: prysm
    validator_count: 32
    count: 2
# Ethereum nodes for diva connections
# Nodes with 0 validators will be used by diva nodes and connections will be uniformely distributed between them
  - el_type: geth
    cl_type: prysm
    validator_count: 0
    count: 1

additional_services:
  #- tx_spammer
  #- blob_spammer
  #- custom_flood
  #- el_forkmon
  #- beacon_metrics_gazer
  - dora
  #- prometheus_grafana
  #- full_beaconchain_explorer
  - blockscout
  - assertoor

persistent: false
mev_type: null