network_params:
  network_id: "3151908"
  genesis_delay: 60
  deneb_fork_epoch: 0
  electra_fork_epoch: 999999
  preregistered_validator_count: -1 # This is overwritten by DIVA constants

additional_services:
  #- tx_spammer
  #- blob_spammer
  #- custom_flood
  #- el_forkmon
  #- beacon_metrics_gazer
  - dora
  #- prometheus_grafana
  #- full_beaconchain_explorer

mev_type: none

participants:
  # first pair must be geth & nimbus to expose public ports if you use shamir eth-pack
  # first cl must be lighthouse or prysm for beaconchain explorer to work
  - el_type: geth
    cl_type: prysm
    validator_count: 32

  - el_type: geth
    cl_type: prysm
    validator_count: 0

  - el_type: geth
    cl_type: lighthouse
    validator_count: 32

diva_params:
  deployment:
    deploy_eth: true
    deploy_diva_sc: true
    deploy_diva_coord_boot: true
    deploy_diva: false
    deploy_operator_ui: false
    options:
      charge_pre_genesis_keys: false
      public_ports: true

  protocol_features:
    verify_fee_recipient: false
    private_pools_only: true
  
persistent: false

mev_params:
  launch_custom_flood: true
  mev_relay_image: flashbots/mev-boost-relay:latest
mev_type: null
